# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SitnuWatch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SitnuWatch

  target 'SitnuWatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SitnuWatch-Watch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SitnuWatch-Watch
  pod 'WebUntis', :path => '../../WebUntis'#, :git => 'https://github.com/TheNoim/WebUntis-Swift.git'
  pod 'Locksmith'
end

target 'SitnuWatch-Watch Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SitnuWatch-Watch Extension
  pod 'WebUntis', :path => '../../WebUntis'#, :git => 'https://github.com/TheNoim/WebUntis-Swift.git'
  pod 'Locksmith'
end
